/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;


import Controle.ConectaBanco;

/**
 *
 * @author tsilva
 */
public class FormularioPrincipal extends javax.swing.JFrame {
    
    ConectaBanco conexao = new ConectaBanco();

    /**
     * Creates new form FormularioPrincipal
     */
    public FormularioPrincipal() {
        initComponents();
        conexao.Conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jTelefone = new javax.swing.JMenu();
        jMenuEstado = new javax.swing.JMenuItem();
        jMenuCidade = new javax.swing.JMenuItem();
        jMenuBairro = new javax.swing.JMenuItem();
        jMenuTelefone = new javax.swing.JMenuItem();
        jMenuCliente = new javax.swing.JMenuItem();
        jMenuProduto = new javax.swing.JMenuItem();
        jMenuFornecedor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Pizzaria");
        setBackground(new java.awt.Color(255, 255, 51));
        setResizable(false);

        jTelefone.setText("CADASTROS");
        jTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTelefoneActionPerformed(evt);
            }
        });

        jMenuEstado.setText("ESTADO");
        jMenuEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEstadoActionPerformed(evt);
            }
        });
        jTelefone.add(jMenuEstado);

        jMenuCidade.setText("CIDADE");
        jMenuCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCidadeActionPerformed(evt);
            }
        });
        jTelefone.add(jMenuCidade);

        jMenuBairro.setText("BAIRRO");
        jMenuBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBairroActionPerformed(evt);
            }
        });
        jTelefone.add(jMenuBairro);

        jMenuTelefone.setText("TELEFONE");
        jMenuTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTelefoneActionPerformed(evt);
            }
        });
        jTelefone.add(jMenuTelefone);

        jMenuCliente.setText("CLIENTE");
        jMenuCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClienteActionPerformed(evt);
            }
        });
        jTelefone.add(jMenuCliente);

        jMenuProduto.setText("PRODUTO");
        jTelefone.add(jMenuProduto);

        jMenuFornecedor.setText("FORNECEDOR");
        jTelefone.add(jMenuFornecedor);

        jMenuBar1.add(jTelefone);

        jMenu2.setText("COMPRA");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("VENDA");
        jMenuBar1.add(jMenu3);

        jMenu4.setText("RELATORIOS");
        jMenuBar1.add(jMenu4);

        jMenu5.setText("SAIR");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1127, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1135, 676));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClienteActionPerformed
        // TODO add your handling code here:
         FrmCliente frm = new FrmCliente();
           frm.setVisible(true);
    }//GEN-LAST:event_jMenuClienteActionPerformed

    private void jMenuBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBairroActionPerformed
        // TODO add your handling code here:
           FrmBairro frm = new FrmBairro();
           frm.setVisible(true);
    }//GEN-LAST:event_jMenuBairroActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        conexao.desconecta(); 
        System.exit(0);
               // TODO add your handling code here:
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEstadoActionPerformed
        // TODO add your handling code here:
        FrmEstado frm = new FrmEstado();
        frm.setVisible(true);
    }//GEN-LAST:event_jMenuEstadoActionPerformed

    private void jMenuCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCidadeActionPerformed
        // TODO add your handling code here:
        FrmCidade frm = new FrmCidade();
        frm.setVisible(true);
        
    }//GEN-LAST:event_jMenuCidadeActionPerformed

    private void jTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTelefoneActionPerformed
        // TODO add your handling code here:
       FrmTelefone frm = new FrmTelefone();
       frm.setVisible(true);
    }//GEN-LAST:event_jTelefoneActionPerformed

    private void jMenuTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTelefoneActionPerformed
        // TODO add your handling code here:
          FrmTelefone frm = new FrmTelefone();
       frm.setVisible(true);
    }//GEN-LAST:event_jMenuTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuBairro;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCidade;
    private javax.swing.JMenuItem jMenuCliente;
    private javax.swing.JMenuItem jMenuEstado;
    private javax.swing.JMenuItem jMenuFornecedor;
    private javax.swing.JMenuItem jMenuProduto;
    private javax.swing.JMenuItem jMenuTelefone;
    private javax.swing.JMenu jTelefone;
    // End of variables declaration//GEN-END:variables

  
}
