/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.ConectaBanco;
import Controle.ControleBairro;
import Modelo.ModeloBairro;

import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import Controle.ModeloTabela;
/**
 *
 * @author thiago
 */
public class FrmBairro extends javax.swing.JFrame {

    
  ConectaBanco conexao = new ConectaBanco();
    
     ConectaBanco connCidade = new ConectaBanco();
     ConectaBanco connBairro = new ConectaBanco();
         ModeloBairro mod = new ModeloBairro();
            ControleBairro control= new ControleBairro();      /**
     * Creates new form FrmBairro
     */
    public FrmBairro() {
        initComponents();
           conexao.Conexao();
        
         connCidade.Conexao();
         connBairro.Conexao();
           PreencherTabela("SELECT *  FROM bairro INNER JOIN cidade  ON BAIRRO.COD_CIDADE = CIDADE.ID_CIDADE ");
         connCidade.executaSql(" SELECT * FROM cidade ORDER BY NOME_CIDADE ");
         jComboBox1.removeAllItems();
         try{
             connCidade.rs.first();
             do{
               jComboBox1.addItem(connCidade.rs.getString("NOME_CIDADE"));
             }while(connCidade.rs.next());
             
         }catch(SQLException e){
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a lista"+e);
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCodBairro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtBairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCidade = new javax.swing.JTable();
        jBnNovobai = new javax.swing.JButton();
        jBnEditBai = new javax.swing.JButton();
        jBtnExcluiBai = new javax.swing.JButton();
        jBnSalvarBai = new javax.swing.JButton();
        jButtonPrimeiroBai = new javax.swing.JButton();
        jButtonAnteriorBai = new javax.swing.JButton();
        jButtonProximoBai = new javax.swing.JButton();
        jButtonUltimoBai = new javax.swing.JButton();
        jBnSairBai = new javax.swing.JButton();
        jButtonBai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO DE CADASTRO DE BAIRRO");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Codigo");

        jTxtCodBairro.setEnabled(false);

        jLabel3.setText("Nome");

        jTxtBairro.setEnabled(false);

        jLabel4.setText("CIDADE");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableCidade);

        jBnNovobai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jBnNovobai.setToolTipText("Novo");
        jBnNovobai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnNovobaiActionPerformed(evt);
            }
        });

        jBnEditBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jBnEditBai.setToolTipText("Editar");
        jBnEditBai.setEnabled(false);
        jBnEditBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnEditBaiActionPerformed(evt);
            }
        });

        jBtnExcluiBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jBtnExcluiBai.setToolTipText("Excluir");
        jBtnExcluiBai.setEnabled(false);
        jBtnExcluiBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluiBaiActionPerformed(evt);
            }
        });

        jBnSalvarBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save1.png"))); // NOI18N
        jBnSalvarBai.setToolTipText("Salvar");
        jBnSalvarBai.setEnabled(false);
        jBnSalvarBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnSalvarBaiActionPerformed(evt);
            }
        });

        jButtonPrimeiroBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro.png"))); // NOI18N
        jButtonPrimeiroBai.setToolTipText("Primeiro");
        jButtonPrimeiroBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroBaiActionPerformed(evt);
            }
        });

        jButtonAnteriorBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        jButtonAnteriorBai.setToolTipText("Anterior");
        jButtonAnteriorBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorBaiActionPerformed(evt);
            }
        });

        jButtonProximoBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo.png"))); // NOI18N
        jButtonProximoBai.setToolTipText("Próximo");
        jButtonProximoBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoBaiActionPerformed(evt);
            }
        });

        jButtonUltimoBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultmio2.png"))); // NOI18N
        jButtonUltimoBai.setToolTipText("ultimo");
        jButtonUltimoBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoBaiActionPerformed(evt);
            }
        });

        jBnSairBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jBnSairBai.setToolTipText("Sair");
        jBnSairBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnSairBaiActionPerformed(evt);
            }
        });

        jButtonBai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_download_cancel_103531.png"))); // NOI18N
        jButtonBai.setToolTipText("Cancelar");
        jButtonBai.setEnabled(false);
        jButtonBai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBnNovobai, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBnEditBai)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluiBai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBnSalvarBai, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonPrimeiroBai)
                .addGap(18, 18, 18)
                .addComponent(jButtonAnteriorBai)
                .addGap(18, 18, 18)
                .addComponent(jButtonProximoBai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUltimoBai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBnSairBai)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTxtCodBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtCodBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBnNovobai, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jBnEditBai)
                            .addComponent(jBtnExcluiBai)
                            .addComponent(jBnSalvarBai, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jButtonPrimeiroBai)
                            .addComponent(jButtonAnteriorBai)
                            .addComponent(jButtonProximoBai)
                            .addComponent(jButtonUltimoBai)
                            .addComponent(jButtonBai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jBnSairBai, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnNovobaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnNovobaiActionPerformed
        // TODO add your handling code here:

        jTxtBairro.setEnabled(true);

        jBnEditBai.setEnabled(true);
        jBtnExcluiBai.setEnabled(true);
        jBnSalvarBai.setEnabled(true);
        jButtonBai.setEnabled(true);

        jTxtCodBairro.setText(" ");
        jTxtBairro.setText(" ");
        jBnNovobai.setEnabled(false);
    }//GEN-LAST:event_jBnNovobaiActionPerformed

    private void jBnEditBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnEditBaiActionPerformed
        // TODO add your handling code here:
        try {

            mod.setIdBairro(Integer.parseInt(jTxtCodBairro.getText()));
            mod.setNomeBairro(jTxtBairro.getText());
            connBairro.executaSql("SELECT * FROM cidade WHERE NOME_cidade ='"+jComboBox1.getSelectedItem()+"'");
            connBairro.rs.first();
            mod.setCodCidade(connBairro.rs.getInt("id_cidade"));
            control.AlterarBairro(mod);
            PreencherTabela("SELECT *  FROM bairro INNER JOIN cidade  ON BAIRRO.COD_CIDADE = CIDADE.ID_CIDADE ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro na edição \n Erro"+ex);
        }

    }//GEN-LAST:event_jBnEditBaiActionPerformed

    private void jBtnExcluiBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluiBaiActionPerformed
        try {

            mod.setIdBairro(Integer.parseInt(jTxtCodBairro.getText()));
            mod.setNomeBairro(jTxtBairro.getText());
            mod.setCodCidade(connCidade.rs.getInt("cod_cidade"));
            control.ExcluiBairro(mod);
            PreencherTabela("SELECT *  FROM bairro INNER JOIN cidade  ON BAIRRO.COD_CIDADE = CIDADE.ID_CIDADE ");
            jTxtBairro.setEnabled(false);

            jBnEditBai.setEnabled(false);
            jBtnExcluiBai.setEnabled(false);
            jBnSalvarBai.setEnabled(false);
            jButtonBai.setEnabled(false);

            jTxtCodBairro.setText(" ");
            jTxtBairro.setText(" ");
            jBnNovobai.setEnabled(true);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro na Exclusão \n Erro"+ex);
        }

    }//GEN-LAST:event_jBtnExcluiBaiActionPerformed

    private void jBnSalvarBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnSalvarBaiActionPerformed
        // TODO add your handling code here:

        try {

            mod.setNomeBairro(jTxtBairro.getText());
            connCidade.executaSql("SELECT * FROM CIDADE WHERE NOME_CIDADE ='"+jComboBox1.getSelectedItem()+"'");
            connCidade.rs.first();
            mod.setCodCidade(connCidade.rs.getInt("id_cidade"));

            control.InserirBairro(mod);
            PreencherTabela("SELECT *  FROM bairro INNER JOIN cidade  ON BAIRRO.COD_CIDADE = CIDADE.ID_CIDADE ");
            jTxtBairro.setEnabled(false);

            jBnEditBai.setEnabled(false);
            jBtnExcluiBai.setEnabled(false);
            jBnSalvarBai.setEnabled(false);
            jButtonBai.setEnabled(false);

            jTxtCodBairro.setText(" ");
            jTxtBairro.setText(" ");
            jBnNovobai.setEnabled(true);
        } catch (SQLException ex) {
            Logger.getLogger(FrmCidade.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBnSalvarBaiActionPerformed

    private void jButtonPrimeiroBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroBaiActionPerformed
        // TODO add your handling code here:
        jBnEditBai.setEnabled(true);
        jBtnExcluiBai.setEnabled(true);

        jButtonBai.setEnabled(true);
        jBnNovobai.setEnabled(false);
        jTxtBairro.setEnabled(true);

        try{
            connBairro.executaSql(" select * from bairro order by id_bairro");
            connBairro.rs.first();
            jTxtCodBairro.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTxtBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSql(" select * from cidade where id_cidade="+connBairro.rs.getInt("cod_cidade"));
            connCidade.rs.first();
            jComboBox1.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonPrimeiroBaiActionPerformed

    private void jButtonAnteriorBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorBaiActionPerformed
        jBnEditBai.setEnabled(true);
        jBtnExcluiBai.setEnabled(true);

        jButtonBai.setEnabled(true);
        jBnNovobai.setEnabled(false);
        jTxtBairro.setEnabled(true);
         try{
            connBairro.executaSql(" select * from bairro order by id_bairro");
            connBairro.rs.previous();
            jTxtCodBairro.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTxtBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSql(" select * from cidade where id_cidade="+connBairro.rs.getInt("cod_cidade"));
            connCidade.rs.first();
            jComboBox1.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonAnteriorBaiActionPerformed

    private void jButtonProximoBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoBaiActionPerformed
        // TODO add your handling code here:
        jBnEditBai.setEnabled(true);
        jBtnExcluiBai.setEnabled(true);

        jButtonBai.setEnabled(true);
        jBnNovobai.setEnabled(false);
        jTxtBairro.setEnabled(true);
        try{
            connBairro.executaSql(" select * from bairro order by id_bairro");
            connBairro.rs.next();
            jTxtCodBairro.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTxtBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSql(" select * from cidade where id_cidade="+connBairro.rs.getInt("cod_cidade"));
            connCidade.rs.first();
            jComboBox1.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonProximoBaiActionPerformed

    private void jButtonUltimoBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoBaiActionPerformed
        // TODO add your handling code here:

        jBnEditBai.setEnabled(true);
        jBtnExcluiBai.setEnabled(true);

        jButtonBai.setEnabled(true);
        jBnNovobai.setEnabled(false);
        jTxtBairro.setEnabled(true);

        try{
            connBairro.executaSql(" select * from bairro order by id_bairro");
            connBairro.rs.last();
            jTxtCodBairro.setText(String.valueOf(connBairro.rs.getInt("id_bairro")));
            jTxtBairro.setText(connBairro.rs.getString("nome_bairro"));
            connCidade.executaSql(" select * from cidade where id_cidade="+connBairro.rs.getInt("cod_cidade"));
            connCidade.rs.first();
            jComboBox1.setSelectedItem(connCidade.rs.getString("nome_cidade"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonUltimoBaiActionPerformed

    private void jBnSairBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnSairBaiActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBnSairBaiActionPerformed

    private void jButtonBaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBaiActionPerformed
        // TODO add your handling code here:

        jTxtBairro.setEnabled(false);

        jBnEditBai.setEnabled(false);
        jBtnExcluiBai.setEnabled(false);
        jBnSalvarBai.setEnabled(false);
        jButtonBai.setEnabled(false);

        jTxtCodBairro.setText(" ");
        jTxtBairro.setText(" ");
        jBnNovobai.setEnabled(true);
    }//GEN-LAST:event_jButtonBaiActionPerformed
          public void PreencherTabela(String SQL){
       ArrayList Dados = new ArrayList(); 
        String [] Colunas = new String[]{"ID","BAIRRO","CIDADE"};
        
       connBairro.executaSql(SQL);
        try{
           connBairro.rs.first();
            do{
                Dados.add(new Object[]{connBairro.rs.getInt("id_bairro"),connBairro.rs.getString("nome_Bairro"),connBairro.rs.getString("nome_cidade")});
            }while(connBairro.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher \n Erro"+ex);
           }    
          ModeloTabela modelo  = new ModeloTabela(Dados,Colunas);
          jTableCidade.setModel(modelo);
          jTableCidade.getColumnModel().getColumn(0).setPreferredWidth(105);
          jTableCidade.getColumnModel().getColumn(0).setResizable(false);
          jTableCidade.getColumnModel().getColumn(1).setPreferredWidth(280);
          jTableCidade.getColumnModel().getColumn(1).setResizable(false);
          jTableCidade.getColumnModel().getColumn(2).setPreferredWidth(105);
          jTableCidade.getColumnModel().getColumn(2).setResizable(false);
          jTableCidade.getTableHeader().setReorderingAllowed(false);
          jTableCidade.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
         jTableCidade.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBairro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBairro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnEditBai;
    private javax.swing.JButton jBnNovobai;
    private javax.swing.JButton jBnSairBai;
    private javax.swing.JButton jBnSalvarBai;
    private javax.swing.JButton jBtnExcluiBai;
    private javax.swing.JButton jButtonAnteriorBai;
    private javax.swing.JButton jButtonBai;
    private javax.swing.JButton jButtonPrimeiroBai;
    private javax.swing.JButton jButtonProximoBai;
    private javax.swing.JButton jButtonUltimoBai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCidade;
    private javax.swing.JTextField jTxtBairro;
    private javax.swing.JTextField jTxtCodBairro;
    // End of variables declaration//GEN-END:variables
}
