/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.ConectaBanco;
import Controle.ControleCidade;
import Modelo.ModeloCidade;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import Controle.ModeloTabela;

/**
 *
 * @author tsilva
 */
public class FrmCidade extends javax.swing.JFrame {

     ConectaBanco conexao = new ConectaBanco();
     ConectaBanco connEstado =new ConectaBanco();
     ConectaBanco connCidade = new ConectaBanco();
         ModeloCidade mod = new ModeloCidade();
            ControleCidade control= new ControleCidade();   
    /**
     * Creates new form FrmBairro
     */
    public FrmCidade() {
        initComponents();
         conexao.Conexao();
         connEstado.Conexao();
         connCidade.Conexao();
           PreencherTabela("SELECT *  FROM cidade INNER JOIN ESTADO  ON CIDADE.COD_ESTADO = ESTADO.ID_ESTADO ");
         connEstado.executaSql(" SELECT * FROM ESTADO ORDER BY NOME_ESTADO ");
         jComboBox1.removeAllItems();
         try{
             connEstado.rs.first();
             do{
               jComboBox1.addItem(connEstado.rs.getString("NOME_ESTADO"));
             }while(connEstado.rs.next());
             
         }catch(SQLException e){
             JOptionPane.showMessageDialog(rootPane,"Erro ao preencher a lista"+e);
         }
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTxtCodCidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxtCidade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCidade = new javax.swing.JTable();
        jBnNovoCid = new javax.swing.JButton();
        jBnEditCid = new javax.swing.JButton();
        jBtnExcluirCid = new javax.swing.JButton();
        jBnSalvarCid = new javax.swing.JButton();
        jButtonPrimeiroCid = new javax.swing.JButton();
        jButtonAnteriorCid = new javax.swing.JButton();
        jButtonProximoCid = new javax.swing.JButton();
        jButtonUltimoCid = new javax.swing.JButton();
        jBnSairCid = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Codigo");

        jLabel3.setText("Nome");

        jLabel4.setText("Estado");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTableCidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableCidade);

        jBnNovoCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jBnNovoCid.setToolTipText("Novo");
        jBnNovoCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnNovoCidActionPerformed(evt);
            }
        });

        jBnEditCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jBnEditCid.setToolTipText("Editar");
        jBnEditCid.setEnabled(false);
        jBnEditCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnEditCidActionPerformed(evt);
            }
        });

        jBtnExcluirCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jBtnExcluirCid.setToolTipText("Excluir");
        jBtnExcluirCid.setEnabled(false);
        jBtnExcluirCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirCidActionPerformed(evt);
            }
        });

        jBnSalvarCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save1.png"))); // NOI18N
        jBnSalvarCid.setToolTipText("Salvar");
        jBnSalvarCid.setEnabled(false);
        jBnSalvarCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnSalvarCidActionPerformed(evt);
            }
        });

        jButtonPrimeiroCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro.png"))); // NOI18N
        jButtonPrimeiroCid.setToolTipText("Primeiro");
        jButtonPrimeiroCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroCidActionPerformed(evt);
            }
        });

        jButtonAnteriorCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        jButtonAnteriorCid.setToolTipText("Anterior");
        jButtonAnteriorCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorCidActionPerformed(evt);
            }
        });

        jButtonProximoCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo.png"))); // NOI18N
        jButtonProximoCid.setToolTipText("Próximo");
        jButtonProximoCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoCidActionPerformed(evt);
            }
        });

        jButtonUltimoCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultmio2.png"))); // NOI18N
        jButtonUltimoCid.setToolTipText("ultimo");
        jButtonUltimoCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoCidActionPerformed(evt);
            }
        });

        jBnSairCid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jBnSairCid.setToolTipText("Sair");
        jBnSairCid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnSairCidActionPerformed(evt);
            }
        });

        jButtonCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_download_cancel_103531.png"))); // NOI18N
        jButtonCancelar.setToolTipText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBnNovoCid, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBnEditCid)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnExcluirCid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBnSalvarCid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPrimeiroCid)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonAnteriorCid)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonProximoCid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonUltimoCid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jBnSairCid))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jTxtCodCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTxtCodCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTxtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jBnNovoCid, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jBnEditCid)
                            .addComponent(jBtnExcluirCid)
                            .addComponent(jBnSalvarCid, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                            .addComponent(jButtonPrimeiroCid)
                            .addComponent(jButtonAnteriorCid)
                            .addComponent(jButtonProximoCid)
                            .addComponent(jButtonUltimoCid)
                            .addComponent(jButtonCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jBnSairCid, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORMULARIO DE CADASTRO DE CIDADE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(882, 434));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBnNovoCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnNovoCidActionPerformed
        // TODO add your handling code here:
        
        jTxtCidade.setEnabled(true);
       
        jBnEditCid.setEnabled(true);
        jBtnExcluirCid.setEnabled(true);
        jBnSalvarCid.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
       jTxtCodCidade.setText(" ");
        jTxtCidade.setText(" ");
        jBnNovoCid.setEnabled(false);

    }//GEN-LAST:event_jBnNovoCidActionPerformed

    private void jBnEditCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnEditCidActionPerformed
        // TODO add your handling code here:
        try {
         
             mod.setCod(Integer.parseInt(jTxtCodCidade.getText()));
             mod.setNome(jTxtCidade.getText());
             connCidade.executaSql("SELECT * FROM ESTADO WHERE NOME_ESTADO ='"+jComboBox1.getSelectedItem()+"'");
              connCidade.rs.first();
             mod.setCod_estado(connCidade.rs.getInt("id_estado"));
             control.AlterarCidade(mod);
               PreencherTabela("SELECT *  FROM cidade INNER JOIN ESTADO  ON CIDADE.COD_ESTADO = ESTADO.ID_ESTADO ");
         } catch (SQLException ex) {
               JOptionPane.showMessageDialog(rootPane,"Erro na edição \n Erro"+ex);
         }
        
    }//GEN-LAST:event_jBnEditCidActionPerformed

    private void jBtnExcluirCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirCidActionPerformed
         try {
         
             mod.setCod(Integer.parseInt(jTxtCodCidade.getText()));
             mod.setNome(jTxtCidade.getText());
             mod.setCod_estado(connCidade.rs.getInt("cod_estado"));
             control.ExcluiCidade(mod);
            PreencherTabela("SELECT *  FROM cidade INNER JOIN ESTADO  ON CIDADE.COD_ESTADO = ESTADO.ID_ESTADO ");
                jTxtCidade.setEnabled(false);
       
        jBnEditCid.setEnabled(false);
        jBtnExcluirCid.setEnabled(false);
        jBnSalvarCid.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
       jTxtCodCidade.setText(" ");
        jTxtCidade.setText(" ");
        jBnNovoCid.setEnabled(true);
         } catch (SQLException ex) {
              JOptionPane.showMessageDialog(rootPane,"Erro na Exclusão \n Erro"+ex);
         }
         
    }//GEN-LAST:event_jBtnExcluirCidActionPerformed

    private void jBnSalvarCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnSalvarCidActionPerformed
        // TODO add your handling code here:
       
         try {
         
             mod.setNome(jTxtCidade.getText());
             connEstado.executaSql("SELECT * FROM ESTADO WHERE NOME_ESTADO ='"+jComboBox1.getSelectedItem()+"'");
             connEstado.rs.first();
               mod.setCod_estado(connEstado.rs.getInt("id_estado"));
             
               control.InserirCidade(mod);
               PreencherTabela("SELECT *  FROM cidade INNER JOIN ESTADO  ON CIDADE.COD_ESTADO = ESTADO.ID_ESTADO ");
               jTxtCidade.setEnabled(false);
       
        jBnEditCid.setEnabled(false);
        jBtnExcluirCid.setEnabled(false);
        jBnSalvarCid.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
       jTxtCodCidade.setText(" ");
        jTxtCidade.setText(" ");
        jBnNovoCid.setEnabled(true);
         } catch (SQLException ex) {
             Logger.getLogger(FrmCidade.class.getName()).log(Level.SEVERE, null, ex);
         }
      
        
    }//GEN-LAST:event_jBnSalvarCidActionPerformed

    private void jButtonPrimeiroCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroCidActionPerformed
        // TODO add your handling code here:
                   jBnEditCid.setEnabled(true);
        jBtnExcluirCid.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jBnNovoCid.setEnabled(false);
        jTxtCidade.setEnabled(true);

        try{
            connCidade.executaSql(" select * from cidade order by id_cidade");
            connCidade.rs.first();
            jTxtCodCidade.setText(String.valueOf(connCidade.rs.getInt("id_cidade")));
            jTxtCidade.setText(connCidade.rs.getString("nome_cidade"));
            connEstado.executaSql(" select * from estado where id_estado="+connCidade.rs.getInt("cod_estado"));
            connEstado.rs.first();
            jComboBox1.setSelectedItem(connEstado.rs.getString("nome_estado"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonPrimeiroCidActionPerformed

    private void jButtonAnteriorCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorCidActionPerformed
             jBnEditCid.setEnabled(true);
        jBtnExcluirCid.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jBnNovoCid.setEnabled(false);
          jTxtCidade.setEnabled(true);
       try{
           // connCidade.executaSql(" select * from cidade order by id_cidade");
            connCidade.rs.previous();
            jTxtCodCidade.setText(String.valueOf(connCidade.rs.getInt("id_cidade")));
            jTxtCidade.setText(connCidade.rs.getString("nome_cidade"));
            connEstado.executaSql(" select * from estado where id_estado="+connCidade.rs.getInt("cod_estado"));
            connEstado.rs.first();
            jComboBox1.setSelectedItem(connEstado.rs.getString("nome_estado"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }

    }//GEN-LAST:event_jButtonAnteriorCidActionPerformed

    private void jButtonProximoCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoCidActionPerformed
        // TODO add your handling code here:
              jBnEditCid.setEnabled(true);
        jBtnExcluirCid.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jBnNovoCid.setEnabled(false);
            jTxtCidade.setEnabled(true);                
        try{
          //  connCidade.executaSql(" select * from cidade order by id_cidade");
            connCidade.rs.next();
            jTxtCodCidade.setText(String.valueOf(connCidade.rs.getInt("id_cidade")));
            jTxtCidade.setText(connCidade.rs.getString("nome_cidade"));
            connEstado.executaSql(" select * from estado where id_estado="+connCidade.rs.getInt("cod_estado"));
            connEstado.rs.first();
            jComboBox1.setSelectedItem(connEstado.rs.getString("nome_estado"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonProximoCidActionPerformed

    private void jButtonUltimoCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoCidActionPerformed
        // TODO add your handling code here:
            
             jBnEditCid.setEnabled(true);
        jBtnExcluirCid.setEnabled(true);
        
        jButtonCancelar.setEnabled(true);
        jBnNovoCid.setEnabled(false);
          jTxtCidade.setEnabled(true);
       
        try{
            connCidade.executaSql(" select * from cidade order by id_cidade");
            connCidade.rs.last();
            jTxtCodCidade.setText(String.valueOf(connCidade.rs.getInt("id_cidade")));
            jTxtCidade.setText(connCidade.rs.getString("nome_cidade"));
            connEstado.executaSql(" select * from estado where id_estado="+connCidade.rs.getInt("cod_estado"));
            connEstado.rs.first();
            jComboBox1.setSelectedItem(connEstado.rs.getString("nome_estado"));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);

        }
    }//GEN-LAST:event_jButtonUltimoCidActionPerformed

    private void jBnSairCidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnSairCidActionPerformed
        // TODO add your handling code here:
        dispose();

    }//GEN-LAST:event_jBnSairCidActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
         
        jTxtCidade.setEnabled(false);
       
        jBnEditCid.setEnabled(false);
        jBtnExcluirCid.setEnabled(false);
        jBnSalvarCid.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        
       jTxtCodCidade.setText(" ");
        jTxtCidade.setText(" ");
        jBnNovoCid.setEnabled(true);
    }//GEN-LAST:event_jButtonCancelarActionPerformed
         public void PreencherTabela(String SQL){
       ArrayList Dados = new ArrayList(); 
        String [] Colunas = new String[]{"ID","CIDADE","ESTADO"};
        
       connCidade.executaSql(SQL);
        try{
           connCidade.rs.first();
            do{
                Dados.add(new Object[]{connCidade.rs.getInt("id_cidade"),connCidade.rs.getString("nome_cidade"),connCidade.rs.getString("sigla_estado")});
            }while(connCidade.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher \n Erro"+ex);
           }    
          ModeloTabela modelo  = new ModeloTabela(Dados,Colunas);
          jTableCidade.setModel(modelo);
          jTableCidade.getColumnModel().getColumn(0).setPreferredWidth(105);
          jTableCidade.getColumnModel().getColumn(0).setResizable(false);
          jTableCidade.getColumnModel().getColumn(1).setPreferredWidth(280);
          jTableCidade.getColumnModel().getColumn(1).setResizable(false);
          jTableCidade.getColumnModel().getColumn(2).setPreferredWidth(105);
          jTableCidade.getColumnModel().getColumn(2).setResizable(false);
          jTableCidade.getTableHeader().setReorderingAllowed(false);
          jTableCidade.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
         jTableCidade.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCidade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCidade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnEditCid;
    private javax.swing.JButton jBnNovoCid;
    private javax.swing.JButton jBnSairCid;
    private javax.swing.JButton jBnSalvarCid;
    private javax.swing.JButton jBtnExcluirCid;
    private javax.swing.JButton jButtonAnteriorCid;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonPrimeiroCid;
    private javax.swing.JButton jButtonProximoCid;
    private javax.swing.JButton jButtonUltimoCid;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCidade;
    private javax.swing.JTextField jTxtCidade;
    private javax.swing.JTextField jTxtCodCidade;
    // End of variables declaration//GEN-END:variables
}
