/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import Controle.ConectaBanco;
import java.sql.*;
import java.util.ArrayList;


import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import Controle.ModeloTabela;

/**
 *
 * @author tsilva
 */
public class FrmEstado extends javax.swing.JFrame {
       ConectaBanco conexao = new ConectaBanco();
    /**
     * Creates new form FrmEstado
     */
    public FrmEstado() {
        initComponents();
     
       conexao.Conexao();
       PreencherTabela("SELECT *  FROM ESTADO ORDER BY ID_ESTADO");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextCod = new javax.swing.JTextField();
        jTextNome = new javax.swing.JTextField();
        jTextSigla = new javax.swing.JTextField();
        jBnNovo = new javax.swing.JButton();
        jBnEdit = new javax.swing.JButton();
        jBnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBnSair = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Estado");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Codigo");

        jLabel3.setText("Nome");

        jLabel4.setText("Sigla");

        jTextCod.setEnabled(false);

        jTextNome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextNome.setEnabled(false);

        jTextSigla.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextSigla.setEnabled(false);

        jBnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo.png"))); // NOI18N
        jBnNovo.setToolTipText("Novo");
        jBnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnNovoActionPerformed(evt);
            }
        });

        jBnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/editar.png"))); // NOI18N
        jBnEdit.setToolTipText("Editar");
        jBnEdit.setEnabled(false);
        jBnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnEditActionPerformed(evt);
            }
        });

        jBnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/save1.png"))); // NOI18N
        jBnSalvar.setToolTipText("Salvar");
        jBnSalvar.setEnabled(false);
        jBnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnSalvarActionPerformed(evt);
            }
        });

        jBtnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/excluir.png"))); // NOI18N
        jBtnExcluir.setToolTipText("Excluir");
        jBtnExcluir.setEnabled(false);
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jBnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jBnSair.setToolTipText("Sair");
        jBnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnSairActionPerformed(evt);
            }
        });

        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableEstado);

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/primeiro.png"))); // NOI18N
        jButtonPrimeiro.setToolTipText("Primeiro");
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ultmio2.png"))); // NOI18N
        jButtonUltimo.setToolTipText("ultimo");
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/anterior.png"))); // NOI18N
        jButtonAnterior.setToolTipText("Anterior");
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/proximo.png"))); // NOI18N
        jButtonProximo.setToolTipText("Próximo");
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jBnEdit)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnExcluir)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPrimeiro)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jButtonAnterior)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButtonProximo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButtonUltimo)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBnSair))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))))
                    .addComponent(jBnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jBtnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonAnterior, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonProximo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonUltimo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addComponent(jBnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("FORMULARIO DE CADASTRO DE ESTADO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(214, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(725, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnSalvarActionPerformed
        // TODO add your handling code here:
       String sql = "INSERT INTO estado VALUES (0, ?, ?)";        
        try {
            PreparedStatement ps = conexao.conn.prepareStatement(sql);
            ps.setString(1,jTextNome.getText() );
            ps.setString(2, jTextSigla.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(rootPane,"Inserção Realizada ");
            PreencherTabela("SELECT *  FROM ESTADO ORDER BY ID_ESTADO");
        } catch (SQLException e) {
               JOptionPane.showMessageDialog(rootPane,"Erro na Inserção \n Erro"+e);
        }
        jTextCod.setText(" ");
      jTextNome.setText(" ");
         jTextSigla.setText(" ");
        jTextNome.setEnabled(false);
         jTextSigla.setEnabled(false);
         jBnEdit.setEnabled(false);
         jBtnExcluir.setEnabled(false);
         jBnSalvar.setEnabled(false);
         jBnNovo.setEnabled(true);
    }//GEN-LAST:event_jBnSalvarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
           try {
               // TODO add your handling code here:
//        conexao.executaSql("delete from estado where sigla_estado='"+jTextSigla.getText()+"'");
//        JOptionPane.showMessageDialog(rootPane,"EXCLUIDO COM SUCESSO");
PreparedStatement pst= conexao.conn.prepareStatement("delete from estado where sigla_estado=?");
          pst.setString(1,jTextSigla.getText());
          pst.execute();
              JOptionPane.showMessageDialog(rootPane,"EXCLUIDO COM SUCESSO");
              PreencherTabela("SELECT *  FROM ESTADO ORDER BY ID_ESTADO");
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro na Exclusão \n Erro"+ex);
           }    
             jTextCod.setText(" ");
      jTextNome.setText(" ");
         jTextSigla.setText(" ");
        jTextNome.setEnabled(false);
         jTextSigla.setEnabled(false);
         jBnEdit.setEnabled(false);
         jBtnExcluir.setEnabled(false);
         jBnSalvar.setEnabled(false);
         jBnNovo.setEnabled(true);
    }//GEN-LAST:event_jBtnExcluirActionPerformed
    
    private void jBnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnSairActionPerformed
        // TODO add your handling code here:
        dispose();
        
    }//GEN-LAST:event_jBnSairActionPerformed

    private void jBnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnNovoActionPerformed
        // TODO add your handling code here:
        jTextCod.setText(" ");
         jTextNome.setText(" ");
         jTextSigla.setText(" ");
        jTextNome.setEnabled(true);
         jTextSigla.setEnabled(true);
         jBnEdit.setEnabled(true);
         jBtnExcluir.setEnabled(true);
         jBnSalvar.setEnabled(true);
         jBnNovo.setEnabled(false);
         
    }//GEN-LAST:event_jBnNovoActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        jBnEdit.setEnabled(true);
        jBtnExcluir.setEnabled(true);
         jTextNome.setEnabled(true);
         jTextSigla.setEnabled(true);
        
        
                
      try{
          conexao.executaSql(" select * from estado");
          conexao.rs.first();
          jTextCod.setText(String.valueOf(conexao.rs.getInt("id_estado")));
          jTextNome.setText(conexao.rs.getString("nome_estado"));
          jTextSigla.setText((conexao.rs.getString("sigla_estado")));
      }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);
               
      }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        
        jBnEdit.setEnabled(true);
        jBtnExcluir.setEnabled(true);
         jTextNome.setEnabled(true);
         jTextSigla.setEnabled(true);
         try{
          conexao.executaSql(" select * from estado");
          conexao.rs.last();
          jTextCod.setText(String.valueOf(conexao.rs.getInt("id_estado")));
          jTextNome.setText(conexao.rs.getString("nome_estado"));
          jTextSigla.setText((conexao.rs.getString("sigla_estado")));
      }catch(SQLException e){
          JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+e);
               
      }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
          jBnEdit.setEnabled(true);
        jBtnExcluir.setEnabled(true);
         jTextNome.setEnabled(true);
         jTextSigla.setEnabled(true);
        try {
               // TODO add your handling code here:
               conexao.rs.previous();
                 jTextCod.setText(String.valueOf(conexao.rs.getInt("id_estado")));
          jTextNome.setText(conexao.rs.getString("nome_estado"));
          jTextSigla.setText((conexao.rs.getString("sigla_estado")));
        
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+ex);
           }
        
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
         jBnEdit.setEnabled(true);
        jBtnExcluir.setEnabled(true);
         jTextNome.setEnabled(true);
         jTextSigla.setEnabled(true);
        
          try {
               // TODO add your handling code here:
               conexao.rs.next();
                 jTextCod.setText(String.valueOf(conexao.rs.getInt("id_estado")));
          jTextNome.setText(conexao.rs.getString("nome_estado"));
          jTextSigla.setText((conexao.rs.getString("sigla_estado")));
           } catch (SQLException ex) {
               JOptionPane.showMessageDialog(rootPane,"Erro nos dados \n Erro"+ex);
           }
    }//GEN-LAST:event_jButtonProximoActionPerformed

    private void jBnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnEditActionPerformed
        // TODO add your handling code here:
        try{
        PreparedStatement pst= conexao.conn.prepareStatement("update  estado set nome_estado=?,sigla_estado=? where id_estado=?");
          pst.setString(1,jTextNome.getText());
           pst.setString(2,jTextSigla.getText());
            pst.setInt(3,Integer.parseInt(jTextCod.getText()));
          pst.execute();
              JOptionPane.showMessageDialog(rootPane,"Alterado COM SUCESSO");
              PreencherTabela("SELECT *  FROM ESTADO ORDER BY ID_ESTADO");
           } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro na Alteração \n Erro"+ex);
           }    
    }//GEN-LAST:event_jBnEditActionPerformed
       
    
    
    
    public void PreencherTabela(String SQL){
       ArrayList Dados = new ArrayList(); 
        String [] Colunas = new String[]{"ID","NOME","SIGLA"};
        
        conexao.executaSql(SQL);
        try{
            conexao.rs.first();
            do{
                Dados.add(new Object[]{conexao.rs.getInt("id_estado"),conexao.rs.getString("nome_estado"),conexao.rs.getString("sigla_estado")});
            }while(conexao.rs.next());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao preencher \n Erro"+ex);
           }    
          ModeloTabela modelo  = new ModeloTabela(Dados,Colunas);
          jTableEstado.setModel(modelo);
          jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(105);
          jTableEstado.getColumnModel().getColumn(0).setResizable(false);
          jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(280);
          jTableEstado.getColumnModel().getColumn(1).setResizable(false);
          jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(105);
          jTableEstado.getColumnModel().getColumn(2).setResizable(false);
          jTableEstado.getTableHeader().setReorderingAllowed(false);
          jTableEstado.setAutoResizeMode(jTableEstado.AUTO_RESIZE_OFF);
          jTableEstado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FrmEstado().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBnEdit;
    private javax.swing.JButton jBnNovo;
    private javax.swing.JButton jBnSair;
    private javax.swing.JButton jBnSalvar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextCod;
    private javax.swing.JTextField jTextNome;
    private javax.swing.JTextField jTextSigla;
    // End of variables declaration//GEN-END:variables
}
